"""CHILL CAPYBARA -- writers' room draft: "CURB" angle (draft_larry).

Same format as script.py -- see DESIGN.md section 2.

Barry's comedy here is petty social-etiquette grievances that turn out to be
correct. Every petty thread converges on Mount Snooze in the eruption:

  THREAD                         SETUP                         PAYOFF
  "Who's touching the thermostat?" s01/s03 (no thermostat!)    s08 "The mountain."  s09 Sunny asks it now
  Free oranges / "nothing's free"  s03, orange rolls down s04  s07 orange+rock rain "Free oranges!" s08 "The mountain."
  Orange-hat etiquette / meeting   s01 narrator, s03          s07 the ONE time he wears an orange, it erupts
  Vulture never introduced himself s03 "Gerald." / "no reason" s07 polite goodbye, s08 takes credit, s09 button
  Fish left without saying goodbye s04 (rude!)                s07 Gerald's perfect goodbye = doom, s08 "Oh, now they wave."
  Dormant = asleep = Sunny at noon s04                        s07 eruption
  Catastrophizing / billing        s05 "We're out of time."   s07 shouted at the sky, s08 refund
  Umbrella guy "doesn't need credit" s06                      s08 Barry very much wants the credit
  Signs / rules sign / raft / helmet s06                      s07 helmet saves him, signs + raft save everyone
"""

CAST = {
    "narrator": dict(voice="bm_fable", speed=0.92, name="NARRATOR", color="#E8E8E8"),
    "barry": dict(voice="am_fenrir", speed=1.12, name="BARRY", color="#FFD27A"),
    "sunny": dict(voice="am_onyx", speed=0.90, name="SUNNY", color="#9FE3A8"),
    "doreen": dict(voice="af_heart", speed=0.95, name="DOREEN", color="#FFB0C8"),
    "gerald": dict(voice="bm_george", speed=0.95, name="GERALD", color="#C9B8FF"),
    "shelley": dict(voice="bm_lewis", speed=0.72, name="DR. SHELLEY", color="#A8D8FF"),
}

SCENES = [
    # ------------------------------------------------------------------ COLD OPEN
    dict(id="s01_open", setting="spring_day", music="lounge", events=[
        ("cam", "establishing"),
        ("pause", 1.2),
        ("say", "narrator", "The capybara. The most relaxed animal on Earth."),
        ("cam", "extras"),
        ("say", "narrator", "Birds perch on it. Monkeys nap on it. It wears an orange as a hat, and it never asks why."),
        ("cam", "establishing_push"),
        ("say", "narrator", "Nothing... bothers the capybara.", dict(gap=0.5)),
        ("pause", 0.6),
        ("cam", "barry_cu"),
        ("cue", "barry_reveal", "Barry, in thick round glasses, lifts a thermometer out of the water and squints at it"),
        ("say", "barry", "Thirty-nine point four. Okay. Who's been touching the thermostat?", dict(mood="worried")),
        ("sfx", "record_scratch"),
        ("music", None, dict(fade=0.05)),
        ("pause", 0.5),
        ("say", "narrator", "Almost nothing.", dict(gap=0.2)),
        ("pause", 0.6),
    ]),
    dict(id="s02_title", setting="title", music="jazz_title", tail=0.3, events=[
        ("beat", "title_card", 4.5, "White serif 'CHILL CAPYBARA' on black, Woody-Allen style"),
    ]),

    # ------------------------------------------------------- THE PETTY GRIEVANCES
    dict(id="s03_spring", setting="spring_day", music="lounge", events=[
        ("cam", "trio"),
        ("cue", "barry_holds_thermo", "Barry holds the thermometer up to Sunny like evidence"),
        ("cam", "sunny_cu"),
        ("say", "sunny", "Barry. Bro. There's no thermostat. It's a natural hot spring.", dict(mood="chill", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "Then who's touching it?", dict(mood="worried", to="sunny")),
        ("say", "barry", "Monday, thirty-eight. Tuesday, thirty-eight five. Today, thirty-nine four. That's not nature, Sunny. That's a pattern!", dict(mood="worried", to="sunny")),
        ("cam", "trio"),
        ("say", "doreen", "Barry, honey, put an orange on your head. You'll feel better.", dict(mood="chill", to="barry")),
        ("cue", "doreen_offers_orange", "Doreen nudges an orange across the water toward Barry with her snout"),
        ("say", "barry", "Who decided oranges go on our heads? Was there a meeting? Because nobody invited me to the meeting.", dict(mood="worried", to="doreen")),
        ("cam", "sunny_cu"),
        ("say", "sunny", "It's tradition, bro.", dict(mood="chill")),
        ("cam", "barry_cu"),
        ("say", "barry", "Tradition is just a meeting nobody wrote down!", dict(mood="worried")),
        ("say", "barry", "And where do they even come from? Every morning, a fresh pile. Nobody's paying. Nobody's asking. Nothing is free, Doreen!", dict(mood="worried", to="doreen")),
        ("cam", "trio"),
        ("pause", 0.3),
        ("sfx", "flaps"),
        ("beat", "vulture_lands", 1.6, "Gerald the vulture flaps down and settles onto Barry's head, feet gripping his tuft"),
        ("sfx", "land"),
        ("cam", "barry_cu"),
        ("pause", 0.4),
        ("say", "barry", "And here he is.", dict(mood="deadpan")),
        ("cam", "doreen_cu"),
        ("say", "doreen", "Aww. He likes you.", dict(mood="happy", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "He's a vulture, Doreen. When a vulture likes you, it's not a friendship. It's a waiting list.", dict(mood="deadpan", to="doreen")),
        ("say", "barry", "Six weeks he's been sitting on my head, and he has never once introduced himself. You sit on a guy, you introduce yourself! That's the bare minimum!", dict(mood="worried")),
        ("cam", "gerald_cu"),
        ("say", "gerald", "Gerald.", dict(mood="smug", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "Thank you! Was that so hard?", dict(mood="smug")),
        ("say", "barry", "Now. Why my head, Gerald? There are forty capybaras in this spring.", dict(mood="worried", to="gerald")),
        ("cam", "gerald_cu"),
        ("say", "gerald", "Oh... no reason.", dict(mood="smug", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "No reason. You know who says no reason? Somebody with a reason!", dict(mood="panic")),
    ]),

    # ----------------------------------------------------------- THE EVIDENCE
    dict(id="s04_rumble", setting="spring_day", music=None, events=[
        ("cam", "trio"),
        ("sfx", "rumble_small"),
        ("beat", "rumble1", 2.0, "The ground rumbles: ripples cross the water, everyone's oranges wobble, Gerald grips tighter"),
        ("cam", "volcano"),
        ("beat", "orange_rolls", 2.4, "A single orange tumbles down the green slope of Mount Snooze, bounces off a rock and rolls toward the spring"),
        ("cam", "trio"),
        ("sfx", "splash"),
        ("beat", "orange_plops", 0.8, "The orange plops into the water right beside Barry and bobs there"),
        ("cam", "sunny_cu"),
        ("say", "sunny", "See? The universe provides.", dict(mood="happy")),
        ("cam", "barry_cu"),
        ("say", "barry", "The universe is rumbling, Sunny. And since when does the mountain smoke?", dict(mood="worried")),
        ("cam", "volcano"),
        ("music", "tension", dict(fade=0.4)),
        ("beat", "volcano_puff", 1.5, "Mount Snooze puffs a fat grey smoke cloud"),
        ("cam", "trio"),
        ("say", "doreen", "That's Mount Snooze, sweetie. It's dormant. It's been asleep for a thousand years.", dict(mood="chill", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "Dormant just means sleeping! Sunny sleeps! And every day at noon, Sunny wakes up and eats everything in sight!", dict(mood="panic")),
        ("cam", "sunny_cu"),
        ("pause", 0.3),
        ("say", "sunny", "...Is it noon?", dict(mood="happy")),
        ("cam", "barry_cu"),
        ("say", "barry", "And the fish left! Did anyone notice the fish left?", dict(mood="worried")),
        ("cam", "fish"),
        ("beat", "fish_leave", 2.8, "Three little fish, each carrying a tiny suitcase, hop out of the spring one by one and away over the rocks"),
        ("cam", "trio"),
        ("say", "doreen", "Maybe they're on vacation, honey.", dict(mood="chill")),
        ("say", "barry", "This is the vacation! And not one of them said goodbye. Three summers we share a spring. Not even a note!", dict(mood="worried")),
        ("say", "gerald", "Dreadfully rude, the fish.", dict(mood="neutral")),
        ("cam", "barry_cu"),
        ("say", "barry", "You know who leaves a party without saying goodbye? Somebody who knows the party's about to be on fire!", dict(mood="panic")),
    ]),

    # --------------------------------------------------------------- THERAPY
    dict(id="s05_therapy", setting="therapy_office", music="therapy", transition="fade", events=[
        ("cam", "office_wide"),
        ("cue", "gerald_on_couch", "Barry lies on the log-couch; Gerald is still perched on his head the whole session"),
        ("pause", 0.8),
        ("say", "shelley", "So... Barry. What... brings you in?"),
        ("cam", "barry_couch"),
        ("say", "barry", "Where do I start? The water's getting hotter, the mountain is smoking, the fish packed luggage, and a vulture uses my head as a bench. And I'm the crazy one?", dict(mood="worried", to="shelley")),
        ("cam", "shelley_cu"),
        ("say", "shelley", "This vulture... is he... in the room with us... right now?"),
        ("cam", "office_wide"),
        ("say", "barry", "He's on my head!", dict(mood="panic")),
        ("say", "gerald", "Hello.", dict(mood="neutral", to="shelley")),
        ("pause", 0.5),
        ("say", "shelley", "...Hello."),
        ("cam", "shelley_cu"),
        ("sfx", "paper_scribble"),
        ("beat", "shelley_writes", 1.4, "Dr. Shelley slowly writes on his notepad"),
        ("say", "shelley", "Barry... have you heard... of catastrophizing?"),
        ("say", "shelley", "It's when you... imagine... the worst."),
        ("cam", "window"),
        ("beat", "window_puff", 1.6, "Behind Shelley, through the round window, Mount Snooze puffs a big dark smoke cloud. Shelley doesn't turn around"),
        ("cam", "barry_couch"),
        ("say", "barry", "Okay. And what's it called when the worst is actually happening?", dict(mood="worried", to="shelley")),
        ("cam", "shelley_cu"),
        ("pause", 1.2),
        ("say", "shelley", "...We're out of time."),
        ("cam", "barry_couch"),
        ("say", "barry", "We just sat down!", dict(mood="shock")),
        ("cam", "office_wide"),
        ("say", "shelley", "That'll be... forty oranges."),
        ("say", "barry", "Forty oranges? You charge by the hour, and you talk like that? That's not therapy. That's a business model!", dict(mood="panic", to="shelley")),
        ("pause", 0.4),
        ("cam", "shelley_cu"),
        ("say", "shelley", "...Forty-one."),
    ]),

    # ------------------------------------------------------- PREPARATION MONTAGE
    dict(id="s06_montage", setting="spring_day", music="montage", transition="wipe", events=[
        ("cam", "signs"),
        ("sfx", "hammer"),
        ("beat", "hammer_signs", 3.5, "Barry hammers three wooden signs along a jungle path: 'EXIT ->', 'EVACUATION ROUTE', 'NO, REALLY. THIS WAY.'"),
        ("cam", "rules"),
        ("sfx", "hammer"),
        ("beat", "rules_sign", 3.0, "Barry plants a big sign by the pool: 'SPRING RULES: 1. Introduce yourself 2. Say goodbye 3. No vultures on heads'. Gerald lands on the sign, reads it, then hops onto Barry's head anyway"),
        ("cam", "raft"),
        ("beat", "build_raft", 3.5, "Barry lashes reeds into a raft and raises a little flag: 'S.S. TOLD YOU SO'"),
        ("cam", "helmet"),
        ("beat", "helmet_on", 2.0, "Barry snaps on a tiny red bike helmet and lowers himself into the spring with dignity"),
        ("cam", "trio"),
        ("say", "sunny", "Bro's wearing a helmet... in a hot tub.", dict(mood="happy")),
        ("say", "doreen", "Honey, it's a little paranoid.", dict(mood="happy", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "I'm not paranoid. I'm early.", dict(mood="smug")),
        ("say", "barry", "They laughed at the guy who invented the umbrella, too. Then it rained. And who was dry? Umbrella guy.", dict(mood="smug")),
        ("cam", "trio"),
        ("say", "sunny", "Who invented the umbrella?", dict(mood="chill")),
        ("cam", "barry_cu"),
        ("say", "barry", "I don't know! He's dry! He doesn't need the credit!", dict(mood="worried")),
    ]),

    # ---------------------------------------------------------------- ERUPTION
    dict(id="s07_eruption", setting="spring_evening", music="lounge", events=[
        ("cam", "trio"),
        ("cue", "gerald_on_sign", "Gerald is perched on the SPRING RULES sign, not on Barry"),
        ("say", "doreen", "Barry, honey. One orange. For me.", dict(mood="happy", to="barry")),
        ("pause", 0.5),
        ("say", "barry", "Fine. One orange. But I want it on the record, I'm doing this under protest.", dict(mood="deadpan", to="doreen")),
        ("beat", "barry_orange", 2.0, "Barry takes off the helmet, sets it on a rock, places an orange on his head and closes his eyes"),
        ("music", "serene", dict(fade=1.0)),
        ("cam", "barry_cu"),
        ("say", "barry", "Oh. Oh, wow. This is how you guys feel all day? No wonder nobody notices anything. I could get used to—", dict(mood="chill", cut=5.6)),
        ("cam", "gerald_cu"),
        ("say", "gerald", "Well. I'll be off, then. Goodbye, Barry. Goodbye, everyone. It's been lovely knowing you.", dict(mood="neutral", gap=0.05)),
        ("sfx", "flaps"),
        ("beat", "vulture_leaves", 1.5, "Gerald lifts off the rules sign and flies away, fast, without looking back"),
        ("cam", "barry_cu"),
        ("say", "barry", "See? A proper goodbye. Was that so hard?", dict(mood="chill")),
        ("pause", 0.6),
        ("music", None, dict(fade=0.3)),
        ("beat", "barry_eyes_open", 0.8, "Barry's eyes slowly open behind the glasses"),
        ("say", "barry", "...Why is he saying goodbye?", dict(mood="shock", gap=0.1)),
        ("cam", "thermometer"),
        ("sfx", "glass_pop"),
        ("beat", "thermo_pops", 1.2, "The thermometer's red line shoots to the top and the bulb pops"),
        ("cam", "trio"),
        ("sfx", "rumble_big"),
        ("beat", "big_rumble", 2.0, "Violent rumble; the water starts to boil around them"),
        ("say", "barry", "One orange! I wear one orange!", dict(mood="panic")),
        ("cam", "volcano"),
        ("sfx", "explosion"),
        ("music", "action", dict(fade=0.05)),
        ("beat", "eruption", 3.5, "Mount Snooze erupts: plume, lava fountains, red sky"),
        ("cam", "trio"),
        ("sfx", "rock_whistle"),
        ("beat", "orange_rain", 1.6, "Oranges and small rocks rain out of the sky and plop into the boiling spring"),
        ("say", "sunny", "Whoa! Free oranges!", dict(mood="happy")),
        ("say", "barry", "Nothing is free!", dict(mood="panic")),
        ("sfx", "bonk"), ("sfx", "splat", dict(offset=0.05)),
        ("beat", "doreen_splat", 0.9, "A rock bonks Doreen's orange into juice"),
        ("say", "doreen", "My orange!", dict(mood="shock", gap=0.1)),
        ("beat", "helmet_back", 0.7, "Barry slaps the helmet back on"),
        ("sfx", "bonk"),
        ("beat", "helmet_bonk", 0.8, "A rock bounces harmlessly off Barry's helmet. He doesn't even flinch"),
        ("cam", "barry_cu"),
        ("say", "barry", "Everybody to the raft! Follow the signs! The signs you all laughed at!", dict(mood="panic")),
        ("cam", "escape"),
        ("beat", "run_to_raft", 2.0, "Everyone scrambles out of the spring and runs past the EXIT signs"),
        ("say", "barry", "Is it still catastrophizing if there's a catastrophe?", dict(mood="panic", gap=0.0)),
        ("sfx", "big_splash"),
        ("beat", "raft_launch", 2.5, "They leap onto the raft; it shoots off down the river as lava pours into the spring behind them"),
    ]),

    # --------------------------------------------------------------- AFTERMATH
    dict(id="s08_aftermath", setting="river_sunset", music="sunset", transition="fade", events=[
        ("cam", "raft_wide"),
        ("cue", "gerald_on_flag", "Gerald is perched on top of the raft's flagpole ('S.S. TOLD YOU SO')"),
        ("pause", 1.5),
        ("say", "sunny", "Barry... you were right.", dict(mood="sad", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "Sorry, the river's loud. What was that?", dict(mood="smug", to="sunny")),
        ("cam", "raft_wide"),
        ("say", "sunny", "You were right, bro!", dict(mood="sad")),
        ("say", "doreen", "About everything, honey. The water. The mountain. The fish.", dict(mood="sad", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "And who was touching the thermostat?", dict(mood="smug")),
        ("say", "doreen", "...The mountain.", dict(mood="sad")),
        ("say", "barry", "And where were all the free oranges coming from?", dict(mood="smug")),
        ("say", "sunny", "...The mountain, bro.", dict(mood="sad")),
        ("say", "barry", "The mountain!", dict(mood="happy")),
        ("cam", "gerald_flag"),
        ("say", "gerald", "And, if I may, I did sit on you. Rather a clear sign, I thought.", dict(mood="smug")),
        ("cam", "raft_wide"),
        ("say", "sunny", "Whoa. Gerald totally tried to warn us.", dict(mood="happy")),
        ("say", "doreen", "Thank you, Gerald!", dict(mood="happy", to="gerald")),
        ("cam", "barry_cu"),
        ("say", "barry", "Thank you, Gerald? Six weeks on my head, and all he said was no reason!", dict(mood="panic")),
        ("cam", "gerald_flag"),
        ("say", "gerald", "Among vultures, it's terribly rude to mention it.", dict(mood="neutral")),
        ("cam", "barry_cu"),
        ("say", "barry", "The rude part is not mentioning it!", dict(mood="panic", to="gerald")),
        ("cam", "fish"),
        ("beat", "fish_float_by", 2.5, "The three fish drift past the raft on a lily pad, suitcases stacked, all waving their fins"),
        ("cam", "barry_cu"),
        ("say", "barry", "Oh, now they wave.", dict(mood="deadpan")),
        ("cam", "raft_wide"),
        ("beat", "doreen_orange", 1.2, "Doreen gently places an orange on Barry's helmet"),
        ("say", "barry", "My whole life, I wanted to be right. Now I'm right, I'm homeless, and the vulture's getting the credit.", dict(mood="deadpan")),
        ("pause", 0.8),
        ("say", "barry", "...Still. Pretty, pretty, pretty good.", dict(mood="chill")),
        ("say", "sunny", "Welcome to chill, bro.", dict(mood="happy")),
        ("pause", 1.0),
    ]),

    # ---------------------------------------------------------------- EPILOGUE
    dict(id="s09_epilogue", setting="new_spring", music="lounge", transition="fade", events=[
        ("beat", "three_weeks_later", 2.2, "Caption: THREE WEEKS LATER"),
        ("cam", "sign"),
        ("beat", "sign_reveal", 1.6, "Sign 'SNOOZE SPRINGS 2 -- Barry Approved', with the SPRING RULES sign planted beside it"),
        ("cam", "trio"),
        ("cue", "roles_reversed", "Barry soaks blissfully with an orange on his head, helmet on a rock beside him; Sunny holds the thermometer, worried"),
        ("say", "sunny", "Barry... thirty-nine point two. Who's touching the thermostat?", dict(mood="worried", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "Nobody, Sunny. It's a natural spring.", dict(mood="chill")),
        ("cam", "trio"),
        ("sfx", "flaps"),
        ("beat", "gerald_lands_sunny", 1.6, "Gerald flaps down and lands on Sunny's head"),
        ("sfx", "land"),
        ("say", "gerald", "Gerald. Pleased to meet you.", dict(mood="smug", to="sunny")),
        ("cam", "sunny_cu"),
        ("say", "sunny", "Barry... there's a vulture on my head.", dict(mood="worried")),
        ("cam", "barry_cu"),
        ("say", "barry", "Aww. He likes you.", dict(mood="chill")),
        ("cam", "sunny_cu"),
        ("say", "sunny", "Why my head, Gerald?", dict(mood="worried", to="gerald")),
        ("say", "gerald", "Oh... no reason.", dict(mood="smug")),
        ("cam", "barry_cu"),
        ("pause", 0.4),
        ("beat", "barry_eye_opens", 0.9, "Barry's eyes slowly open"),
        ("beat", "helmet_swap", 1.6, "Barry calmly lifts the orange off his head and straps on the red helmet"),
        ("cam", "trio"),
        ("say", "sunny", "Barry... why are you putting on the helmet?", dict(mood="panic", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "No reason.", dict(mood="smug")),
        ("sfx", "sting_bad"),
        ("pause", 0.6),
    ]),
    dict(id="s10_end", setting="title", music="jazz_end", transition="cut", tail=0.5, events=[
        ("beat", "end_card", 6.0, "'CHILL CAPYBARA' then 'THE END' on black, jazz button"),
    ]),
]
