"""CHILL CAPYBARA — writers' room draft: the WOODY ALLEN angle.

Barry as the verbal, self-deprecating, anxious intellectual: hypochondria (he hopes the
warm water is *him*), his mother, a tortoise therapist too slow to finish the one story
that matters, direct address to the camera, white-on-black title cards with a joke in
the credits. Barry jumps on everybody's lines (small gaps); the chill crowd takes its time.

Every "neurotic" observation pays off in the climax:
  thermometer 39.2 -> 39.6 -> 40.1 -> pops      the smoking "dormant" volcano (it's "well rested")
  the fish leave (one nods at Barry)            Gerald: "How's the heart?" ... then leaves first
  helmet ("fear with a chin strap") saves him   signs ("YES, YOU, SUNNY") + raft S.S. TOLD YOU SO
  Shelley's cliffhanger gets finished three weeks too late.

Same format as script.py — see DESIGN.md §2.
"""

CAST = {
    "narrator": dict(voice="bm_fable", speed=0.92, name="NARRATOR", color="#E8E8E8"),
    "barry": dict(voice="am_fenrir", speed=1.12, name="BARRY", color="#FFD27A"),
    "sunny": dict(voice="am_onyx", speed=0.90, name="SUNNY", color="#9FE3A8"),
    "doreen": dict(voice="af_heart", speed=0.95, name="DOREEN", color="#FFB0C8"),
    "gerald": dict(voice="bm_george", speed=0.95, name="GERALD", color="#C9B8FF"),
    "shelley": dict(voice="bm_lewis", speed=0.72, name="DR. SHELLEY", color="#A8D8FF"),
}

SCENES = [
    # ------------------------------------------------------------------ cold open
    dict(id="s01_open", setting="spring_day", music="lounge", events=[
        ("cam", "establishing"),
        ("pause", 1.0),
        ("say", "narrator", "The capybara. The calmest animal on Earth."),
        ("cam", "extras"),
        ("say", "narrator", "Birds nap on it. Oranges sit on it. It never asks why."),
        ("cam", "establishing_push"),
        ("say", "narrator", "Nothing... troubles the capybara.", dict(gap=0.5)),
        ("pause", 0.6),
        ("cam", "barry_cu"),
        ("cue", "barry_reveal", "Barry, thick round glasses, holds a dripping thermometer up to his face and squints at it"),
        ("say", "barry", "Thirty-nine point two.", dict(mood="worried")),
        ("sfx", "record_scratch"),
        ("music", None, dict(fade=0.05)),
        ("pause", 0.4),
        ("say", "narrator", "Almost nothing.", dict(gap=0.2)),
        ("cue", "barry_to_camera", "Barry turns his face to the camera (direct address) and stays there"),
        ("say", "barry", "Either the spring is getting hotter, or I'm coming down with something. Frankly, I hope it's me. I know how to handle me.", dict(mood="worried", to="camera", gap=0.4)),
        ("pause", 0.5),
    ]),
    # ------------------------------------------------------------------ title
    dict(id="s02_title", setting="title", music="jazz_title", tail=0.3, events=[
        ("beat", "title_card", 3.6, "White Yeseva serif 'CHILL CAPYBARA' centred on black, Woody-Allen style"),
        ("beat", "title_credit", 3.0, "Second card, same style, smaller: 'with MOUNT SNOOZE as itself (dormant)'"),
    ]),
    # ------------------------------------------------------------------ the spring
    dict(id="s03_spring", setting="spring_day", music="lounge", events=[
        ("cam", "trio"),
        ("say", "barry", "Up point six since yesterday. Is anybody writing this down?", dict(mood="worried", to="sunny")),
        ("cam", "sunny_cu"),
        ("say", "sunny", "Bro. It's a hot spring. Hot is, like, the whole brand.", dict(mood="chill", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "Hot is a brand, Sunny. Hotter is soup!", dict(mood="worried", gap=0.1)),
        ("cam", "trio"),
        ("say", "doreen", "Barry, honey. Put an orange on your head. It's very calming.", dict(mood="happy", to="barry")),
        ("cue", "doreen_offers_orange", "Doreen nudges a spare orange across the water toward Barry"),
        ("say", "barry", "I had an orange once. We got very close. Then it went soft, and I had to let it go. I'm not ready for another orange.", dict(mood="sad", to="doreen", gap=0.15)),
        ("pause", 0.3),
        ("sfx", "flaps"),
        ("beat", "vulture_lands", 1.6, "Gerald the vulture flaps down and settles on Barry's head, feet gripping the tuft"),
        ("sfx", "land"),
        ("cam", "barry_cu"),
        ("pause", 0.3),
        ("say", "barry", "And the vulture's back.", dict(mood="deadpan")),
        ("cam", "trio"),
        ("say", "doreen", "Aww. He likes you.", dict(mood="happy")),
        ("say", "barry", "He's not perching, Doreen. He's pre-boarding.", dict(mood="deadpan", gap=0.15)),
        ("cam", "gerald_cu"),
        ("say", "gerald", "Morning, Barry. How's the heart? Any pins and needles?", dict(mood="smug", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "I didn't have pins and needles until you said pins and needles! Now I've got pins! I've got needles! I'm a sewing kit!", dict(mood="panic", gap=0.1)),
        ("cam", "trio"),
        ("say", "sunny", "Bro. Chill is, like, our whole species.", dict(mood="chill")),
        ("say", "barry", "Chill is for animals with nothing to lose, Sunny. I have glasses.", dict(mood="deadpan", gap=0.15)),
    ]),
    # ------------------------------------------------------------------ the rumble
    dict(id="s04_rumble", setting="spring_day", music=None, events=[
        ("cam", "trio"),
        ("sfx", "rumble_small"),
        ("beat", "rumble1", 2.0, "The ground rumbles: ripples cross the water, oranges wobble on heads, Gerald's feathers ruffle"),
        ("say", "barry", "Was that my heart? He mentioned my heart, and now it's doing earthquakes!", dict(mood="panic", gap=0.1)),
        ("cam", "sunny_cu"),
        ("say", "sunny", "Relax, man. That's just Mount Snooze. He snores.", dict(mood="chill")),
        ("cam", "volcano"),
        ("music", "tension", dict(fade=0.4)),
        ("beat", "volcano_puff", 1.6, "Mount Snooze puffs a fat grey smoke ring; a faint orange glow flickers in the crater"),
        ("cam", "barry_cu"),
        ("say", "barry", "He's smoking! That's not asleep. That's pretending to be asleep. I know the look. I do it every night.", dict(mood="worried", gap=0.1)),
        ("cam", "trio"),
        ("say", "doreen", "Sweetie, that mountain has been asleep for a thousand years.", dict(mood="chill", to="barry")),
        ("say", "barry", "Exactly! It's well rested!", dict(mood="panic", gap=0.1)),
        ("sfx", "glass_ping"),
        ("beat", "thermo_check", 1.0, "Barry dips the thermometer and holds it up: it reads 39.6"),
        ("say", "barry", "Thirty-nine point six! It went up while you were reassuring me!", dict(mood="panic", gap=0.1)),
        ("say", "barry", "And the fish are leaving! Fish don't have plans!", dict(mood="worried", gap=0.2)),
        ("cam", "fish"),
        ("sfx", "pop"),
        ("beat", "fish_leave", 2.6, "Three little fish carrying tiny suitcases hop out of the spring single file and away into the jungle"),
        ("beat", "fish_nod", 1.2, "The last fish stops, looks back at Barry, gives one slow solemn nod, and hops off"),
        ("cam", "barry_cu"),
        ("say", "barry", "That fish nodded at me. That's a fish who knows something.", dict(mood="worried", gap=0.2)),
        ("cam", "trio"),
        ("say", "sunny", "Maybe they're on vacation, bro.", dict(mood="chill")),
        ("say", "barry", "From what? They live in a spa!", dict(mood="panic", gap=0.1)),
    ]),
    # ------------------------------------------------------------------ therapy
    dict(id="s05_therapy", setting="therapy_office", music="therapy", transition="fade", events=[
        ("cam", "office_wide"),
        ("pause", 0.6),
        ("cue", "barry_to_camera", "Barry, lying on the log-couch, turns his face to the camera"),
        ("say", "barry", "This is Doctor Shelley. I've been seeing him for six years. He's a tortoise. We're almost up to my childhood.", dict(mood="deadpan", to="camera")),
        ("cam", "shelley_cu"),
        ("say", "shelley", "So... how are we... feeling?", dict(to="barry")),
        ("cam", "barry_couch"),
        ("say", "barry", "How am I feeling? The water's up a degree, the mountain is smoking, the fish packed luggage, and a vulture asked about my heart!", dict(mood="panic", gap=0.1)),
        ("cam", "shelley_cu"),
        ("say", "shelley", "And the volcano... what does it... represent?"),
        ("cam", "barry_couch"),
        ("say", "barry", "Lava! It represents lava! It's not a metaphor, Doc, it's a mountain with a fever!", dict(mood="panic", gap=0.1)),
        ("cam", "shelley_cu"),
        ("sfx", "paper_scribble"),
        ("beat", "shelley_writes", 1.2, "Dr. Shelley very slowly writes one word on his notepad, then underlines it twice"),
        ("say", "shelley", "Perhaps... the volcano... is your—", dict(cut=3.15)),
        ("cam", "barry_couch"),
        ("say", "barry", "My mother is not a volcano! My mother slept through my birth. I had to introduce myself!", dict(mood="panic", gap=-0.15)),
        ("cam", "office_wide"),
        ("pause", 0.5),
        ("say", "shelley", "I remember... the last eruption."),
        ("cam", "barry_couch"),
        ("say", "barry", "You what? When? Was it bad? How bad? Give me a number!", dict(mood="shock", gap=0.1)),
        ("cam", "shelley_cu"),
        ("beat", "hourglass", 1.4, "Dr. Shelley slowly turns his long neck to a little hourglass on the side table; the last grain of sand drops"),
        ("say", "shelley", "Our time... is up."),
        ("cam", "barry_couch"),
        ("say", "barry", "You can't stop there! You're a tortoise! You've had two hundred years to finish that story!", dict(mood="panic", gap=0.1)),
        ("cam", "office_wide"),
        ("say", "shelley", "That'll be... forty oranges."),
        ("pause", 0.4),
        ("say", "barry", "I don't even wear oranges!", dict(mood="deadpan")),
    ]),
    # ------------------------------------------------------------------ montage
    dict(id="s06_montage", setting="spring_day", music="montage", transition="wipe", events=[
        ("cam", "signs"),
        ("sfx", "hammer"), ("sfx", "hammer", dict(offset=0.9)), ("sfx", "hammer", dict(offset=1.8)),
        ("beat", "hammer_signs", 3.2, "Barry hammers arrow signs into the ground along a path: 'EXIT', 'EVACUATION ROUTE', 'STILL THIS WAY', 'YES, YOU, SUNNY'"),
        ("cam", "raft"),
        ("beat", "build_raft", 3.0, "Barry lashes reeds into a raft and hoists a little flag: 'S.S. TOLD YOU SO'"),
        ("cam", "helmet"),
        ("sfx", "zip"),
        ("beat", "helmet_on", 2.0, "Barry snaps on a tiny red bike helmet, tightens the chin strap, and lowers himself back into the spring"),
        ("cam", "trio"),
        ("say", "sunny", "Bro's wearing a helmet... in a hot tub.", dict(mood="happy")),
        ("say", "doreen", "That's very brave, honey.", dict(mood="happy", to="barry")),
        ("say", "barry", "It's not brave, Doreen. Brave is when you're not scared. This is just fear... with a chin strap.", dict(mood="deadpan", gap=0.15)),
        ("cam", "barry_cu"),
        ("say", "barry", "Laugh. They laughed at the first fish to walk on land, too. Look at Gary with his little legs! What's he so worried about? And who's laughing now? Everybody with legs!", dict(mood="smug", gap=0.2)),
        ("cam", "sunny_cu"),
        ("pause", 0.4),
        ("cue", "sunny_looks_down", "Sunny slowly looks down at his own legs under the water"),
        ("say", "sunny", "Whoa. I have legs.", dict(mood="happy")),
    ]),
    # ------------------------------------------------------------------ eruption
    dict(id="s07_eruption", setting="spring_evening", music="lounge", events=[
        ("cam", "trio"),
        ("say", "doreen", "Come on, honey. One orange. For me?", dict(mood="happy", to="barry")),
        ("pause", 0.6),
        ("say", "barry", "Fine. One orange.", dict(mood="deadpan")),
        ("beat", "barry_orange", 2.0, "Barry takes off his helmet and sets it beside him; Doreen places an orange on his head; he closes his eyes"),
        ("music", "serene", dict(fade=1.0)),
        ("cam", "barry_cu"),
        ("say", "barry", "Oh. Oh, this is nice. Is this what you people feel all the time? Even the vulture is—", dict(mood="chill", cut=4.4)),
        ("cam", "gerald_cu"),
        ("say", "gerald", "Well! Lovely knowing you all. Must dash.", dict(mood="happy", gap=0.0)),
        ("sfx", "flaps"),
        ("beat", "vulture_leaves", 1.3, "Gerald launches off Barry's head and flies away very fast; one feather spins down"),
        ("music", None, dict(fade=0.1)),
        ("cam", "thermometer"),
        ("sfx", "glass_pop"),
        ("beat", "thermo_pops", 1.1, "The thermometer's red line shoots to the top and the bulb pops"),
        ("cam", "trio"),
        ("sfx", "rumble_big"), ("sfx", "boil", dict(offset=0.5)),
        ("beat", "big_rumble", 1.8, "Violent rumble; the spring starts to boil; oranges bounce on everyone's heads"),
        ("cam", "barry_cu"),
        ("say", "barry", "Nine seconds. I was chill for nine seconds.", dict(mood="deadpan")),
        ("cam", "volcano"),
        ("sfx", "explosion"),
        ("music", "action", dict(fade=0.05)),
        ("beat", "eruption", 3.2, "Mount Snooze erupts: smoke plume, lava fountains, the sky goes red"),
        ("cam", "trio"),
        ("say", "sunny", "Barry! What do we do?", dict(mood="panic")),
        ("say", "barry", "Oh, now you ask me? Now I'm the expert? Follow my stupid, ridiculous signs!", dict(mood="panic", gap=0.1)),
        ("sfx", "rock_whistle"),
        ("beat", "helmet_back", 0.8, "Barry slaps the helmet back on just as a rock whistles down"),
        ("sfx", "bonk"), ("sfx", "splat", dict(offset=0.5)),
        ("beat", "rocks_fall", 1.6, "Rocks rain down: one bonks off Barry's helmet (dizzy stars), another squashes Doreen's orange into juice"),
        ("say", "doreen", "My orange!", dict(mood="shock", gap=0.1)),
        ("say", "barry", "Fear with a chin strap!", dict(mood="smug", gap=0.1)),
        ("cam", "escape"),
        ("beat", "run_to_raft", 2.0, "Everyone scrambles out of the boiling spring past the EXIT signs; Sunny skids to a stop at 'YES, YOU, SUNNY'"),
        ("say", "sunny", "Aw. He made me a sign.", dict(mood="happy", gap=0.1)),
        ("sfx", "big_splash"),
        ("beat", "raft_launch", 2.4, "They leap onto the raft S.S. TOLD YOU SO, which shoots off downriver as lava pours into the spring behind them"),
    ]),
    # ------------------------------------------------------------------ aftermath
    dict(id="s08_aftermath", setting="river_sunset", music="sunset", transition="fade", events=[
        ("cam", "raft_wide"),
        ("pause", 1.2),
        ("say", "sunny", "Barry... bro... you were right.", dict(mood="sad", to="barry")),
        ("say", "doreen", "About the water. The mountain. The fish.", dict(mood="sad", to="barry")),
        ("cam", "gerald_flag"),
        ("say", "gerald", "And me, to be fair.", dict(mood="smug")),
        ("cam", "barry_cu"),
        ("say", "barry", "Yes. Thank you, Gerald. The omen would like some credit.", dict(mood="deadpan", gap=0.15)),
        ("say", "barry", "Is anybody writing this down?", dict(mood="smug")),
        ("pause", 0.4),
        ("say", "barry", "My whole life, I wanted to be right about something. And now I'm right about everything. It's wonderful. Our home is lava, but it's wonderful.", dict(mood="happy")),
        ("beat", "doreen_orange", 1.2, "Doreen gently places an orange on top of Barry's helmet"),
        ("say", "barry", "Is this it? Am I chill? I think I'm chill.", dict(mood="chill")),
        ("cam", "raft_wide"),
        ("say", "sunny", "Welcome to chill, bro.", dict(mood="happy")),
        ("pause", 0.8),
    ]),
    # ------------------------------------------------------------------ epilogue
    dict(id="s09_epilogue", setting="new_spring", music="lounge", transition="fade", events=[
        ("beat", "three_weeks_later", 2.0, "Caption: THREE WEEKS LATER"),
        ("cam", "trio"),
        ("say", "sunny", "Barry? It's thirty-eight point nine. Should I be tracking this?", dict(mood="worried", to="barry")),
        ("cam", "barry_cu"),
        ("say", "barry", "Sunny. It's a hot spring. Hot is the brand.", dict(mood="chill")),
        ("cam", "wide"),
        ("beat", "shelley_arrives", 2.0, "Dr. Shelley crawls very slowly into frame, dusty and singed, a tiny bindle on a stick"),
        ("say", "shelley", "As I was saying... the last eruption..."),
        ("pause", 0.6),
        ("say", "shelley", "Was... very bad."),
        ("cam", "barry_cu"),
        ("say", "barry", "Yeah. We got that.", dict(mood="deadpan")),
        ("cam", "trio"),
        ("sfx", "flaps"),
        ("beat", "gerald_lands_sunny", 1.6, "Gerald glides in and settles onto Sunny's head"),
        ("sfx", "land"),
        ("say", "sunny", "Barry? There's a vulture on my head.", dict(mood="worried")),
        ("say", "barry", "Aww. He likes you.", dict(mood="smug", to="sunny")),
        ("cam", "gerald_cu"),
        ("say", "gerald", "Lovely morning, Sunny. How's the heart?", dict(mood="smug", to="sunny")),
        ("cam", "trio"),
        ("say", "sunny", "Everybody on the raft!", dict(mood="panic", gap=0.15)),
        ("sfx", "sting_bad"),
    ]),
    # ------------------------------------------------------------------ end titles
    dict(id="s10_end", setting="title", music="jazz_end", transition="cut", tail=0.5, events=[
        ("beat", "end_card", 2.4, "'CHILL CAPYBARA' white serif on black"),
        ("beat", "end_credit_volcano", 2.4, "Next card: 'MOUNT SNOOZE appeared as itself (no longer dormant)'"),
        ("beat", "end_credit_fish", 2.8, "Next card: 'No fish were harmed in the making of this film. They left early.' then jazz button"),
    ]),
]
