"""SEED DRAFT of CHILL CAPYBARA (a starting point for the writers' room).

Same format as script.py — see DESIGN.md §2.
"""

CAST = {
    "narrator": dict(voice="bm_fable", speed=0.92, name="NARRATOR", color="#E8E8E8"),
    "barry": dict(voice="am_fenrir", speed=1.12, name="BARRY", color="#FFD27A"),
    "sunny": dict(voice="am_onyx", speed=0.90, name="SUNNY", color="#9FE3A8"),
    "doreen": dict(voice="af_heart", speed=0.95, name="DOREEN", color="#FFB0C8"),
    "gerald": dict(voice="bm_george", speed=0.95, name="GERALD", color="#C9B8FF"),
    "shelley": dict(voice="bm_lewis", speed=0.72, name="DR. SHELLEY", color="#A8D8FF"),
}

SCENES = [
    dict(id="s01_open", setting="spring_day", music="lounge", events=[
        ("cam", "establishing"),
        ("pause", 1.2),
        ("say", "narrator", "The capybara. The most relaxed creature on Earth."),
        ("cam", "extras"),
        ("say", "narrator", "Birds sit on it. Monkeys nap on it. It soaks in hot springs with an orange on its head, and it never asks why."),
        ("cam", "establishing_push"),
        ("say", "narrator", "Nothing... bothers the capybara.", dict(gap=0.5)),
        ("pause", 0.6),
        ("cam", "barry_cu"),
        ("cue", "barry_reveal", "Barry, in glasses, squints at a thermometer dipped in the water"),
        ("say", "barry", "Thirty-nine point two. That's up point six.", dict(mood="worried")),
        ("sfx", "record_scratch"),
        ("music", None, dict(fade=0.05)),
        ("pause", 0.5),
        ("say", "narrator", "Almost nothing.", dict(gap=0.2)),
        ("pause", 0.6),
    ]),
    dict(id="s02_title", setting="title", music="jazz_title", tail=0.3, events=[
        ("beat", "title_card", 4.5, "White serif 'CHILL CAPYBARA' on black, Woody-Allen style"),
    ]),
    dict(id="s03_spring", setting="spring_day", music="lounge", events=[
        ("cam", "trio"),
        ("say", "barry", "Thirty-nine point two. Yesterday it was thirty-eight six. Is nobody tracking this?", dict(mood="worried", to="sunny")),
        ("cam", "sunny_cu"),
        ("say", "sunny", "Barry. Bro. It's a hot spring. It's supposed to be hot. That's, like, the whole brand.", dict(mood="chill")),
        ("cam", "barry_cu"),
        ("say", "barry", "Hot is fine! Hot is a temperature. Hotter is a trend!", dict(mood="worried")),
        ("cam", "trio"),
        ("say", "doreen", "Barry, honey, put an orange on your head. You'll feel better.", dict(mood="chill", to="barry")),
        ("cue", "doreen_offers_orange", "Doreen nudges an orange toward Barry"),
        ("say", "barry", "Why does everyone keep giving me oranges? Where are they coming from? Has anyone ever met the orange guy?", dict(mood="worried", to="doreen")),
        ("say", "sunny", "The universe provides, man.", dict(mood="chill")),
        ("say", "barry", "The universe doesn't have a produce section, Sunny!", dict(mood="worried")),
        ("pause", 0.4),
        ("sfx", "flaps"),
        ("beat", "vulture_lands", 1.6, "Gerald the vulture flaps down and settles onto Barry's head"),
        ("sfx", "land"),
        ("cam", "barry_cu"),
        ("pause", 0.5),
        ("say", "barry", "And there's a bird on my head again.", dict(mood="deadpan")),
        ("cam", "trio"),
        ("say", "doreen", "Aww. He likes you.", dict(mood="happy")),
        ("say", "barry", "That's a vulture, Doreen. When a vulture sits on you, it's not a compliment. It's a reservation.", dict(mood="worried")),
        ("cam", "gerald_cu"),
        ("say", "gerald", "Oh, don't mind me. Just resting my legs. No reason.", dict(mood="smug")),
        ("cam", "barry_cu"),
        ("say", "barry", "No reason! Did you hear that? Nobody says no reason when there's no reason!", dict(mood="panic")),
        ("cam", "trio"),
        ("say", "sunny", "Bro, you gotta chill. You're the only capybara in history who isn't chill. Scientists are gonna study you.", dict(mood="chill")),
        ("say", "barry", "Good! Let them study me! At least somebody around here will be taking notes!", dict(mood="worried")),
    ]),
    dict(id="s04_rumble", setting="spring_day", music=None, events=[
        ("cam", "trio"),
        ("sfx", "rumble_small"),
        ("beat", "rumble1", 2.2, "The ground rumbles; ripples cross the water; oranges wobble; steam puffs"),
        ("say", "barry", "You felt that. Tell me you felt that.", dict(mood="worried")),
        ("cam", "sunny_cu"),
        ("say", "sunny", "That was my stomach, man. I had, like, eleven melons.", dict(mood="chill")),
        ("cam", "barry_cu"),
        ("say", "barry", "And that? The mountain is smoking. Since when does the mountain smoke?", dict(mood="worried")),
        ("cam", "volcano"),
        ("music", "tension", dict(fade=0.4)),
        ("beat", "volcano_puff", 1.5, "Mount Snooze puffs a bigger smoke cloud"),
        ("cam", "trio"),
        ("say", "doreen", "That's Mount Snooze, sweetie. It's dormant. It's been asleep for a thousand years.", dict(mood="chill")),
        ("cam", "barry_cu"),
        ("say", "barry", "Dormant means asleep! And you know what sleeping things do? They wake up! That's the whole problem with sleep!", dict(mood="panic")),
        ("say", "barry", "And the fish left! Did anybody notice the fish left?", dict(mood="worried")),
        ("cam", "fish"),
        ("beat", "fish_leave", 2.8, "Three fish carrying tiny suitcases hop out of the spring and away"),
        ("cam", "trio"),
        ("say", "sunny", "Maybe they went on vacation, bro.", dict(mood="chill")),
        ("say", "barry", "Where? This is the vacation!", dict(mood="panic")),
    ]),
    dict(id="s05_therapy", setting="therapy_office", music="therapy", transition="fade", events=[
        ("cam", "office_wide"),
        ("pause", 0.8),
        ("say", "shelley", "So... Barry. What's... bothering you?"),
        ("cam", "barry_couch"),
        ("say", "barry", "What's bothering me? The water's getting hotter, the mountain is smoking, the fish packed luggage, and a vulture keeps sitting on my head like I'm a bus stop. And everyone says I'm the problem!", dict(mood="worried")),
        ("say", "barry", "I'm a capybara, Doc. We're supposed to be chill. My mother put an orange on my head the day I was born. I came out wearing produce!", dict(mood="worried")),
        ("cam", "shelley_cu"),
        ("beat", "shelley_writes", 1.2, "Dr. Shelley slowly writes on his notepad"),
        ("say", "shelley", "Barry... I've been a therapist... for a hundred and forty years."),
        ("pause", 0.8),
        ("say", "shelley", "And I think... you need... to relax."),
        ("cam", "barry_couch"),
        ("say", "barry", "A hundred and forty years and that's it? Relax? I could get that from a scented candle!", dict(mood="panic")),
        ("cam", "office_wide"),
        ("say", "shelley", "That'll be... forty oranges."),
        ("pause", 0.5),
        ("say", "barry", "Of course it is.", dict(mood="deadpan")),
    ]),
    dict(id="s06_montage", setting="spring_day", music="montage", transition="wipe", events=[
        ("cam", "signs"),
        ("beat", "hammer_signs", 3.5, "Barry hammers EXIT signs into the ground: 'EXIT →', 'EVACUATION ROUTE', 'NO, REALLY. THIS WAY.'"),
        ("sfx", "hammer"),
        ("cam", "raft"),
        ("beat", "build_raft", 3.5, "Barry lashes reeds into a raft and raises a flag: 'S.S. TOLD YOU SO'"),
        ("cam", "gobag"),
        ("beat", "pack_bag", 3.0, "Items fly into Barry's go-bag: whistle, flashlight, bandages, a tiny map"),
        ("cam", "helmet"),
        ("beat", "helmet_on", 2.0, "Barry snaps on a tiny red bike helmet and lowers himself into the spring"),
        ("cam", "trio"),
        ("say", "sunny", "Bro's wearing a helmet... in a hot tub.", dict(mood="happy")),
        ("say", "doreen", "Barry, the helmet doesn't go with the orange.", dict(mood="happy")),
        ("say", "barry", "I'm not wearing an orange!", dict(mood="worried")),
        ("cam", "barry_cu"),
        ("say", "barry", "Laugh it up. You know who else they laughed at? Noah. Big boat guy. And who was laughing at the end? Not the people without a boat, I'll tell you that.", dict(mood="smug")),
    ]),
    dict(id="s07_eruption", setting="spring_evening", music="lounge", events=[
        ("cam", "trio"),
        ("say", "doreen", "Come on, Barry. One orange. For me.", dict(mood="happy", to="barry")),
        ("pause", 0.6),
        ("say", "barry", "Fine. One orange.", dict(mood="deadpan")),
        ("beat", "barry_orange", 2.0, "Barry takes off the helmet and places an orange on his head; closes his eyes"),
        ("music", "serene", dict(fade=1.0)),
        ("cam", "barry_cu"),
        ("say", "barry", "Oh. Oh, this is nice. Is this what it's like? You guys feel like this all the time? Why did nobody tell me—", dict(mood="chill", cut=5.2)),
        ("cam", "gerald_cu"),
        ("say", "gerald", "Right then. Lovely chatting. Must dash.", dict(mood="neutral", gap=0.0)),
        ("sfx", "flaps"),
        ("beat", "vulture_leaves", 1.5, "Gerald takes off and flies away fast"),
        ("music", None, dict(fade=0.1)),
        ("cam", "thermometer"),
        ("sfx", "glass_pop"),
        ("beat", "thermo_pops", 1.2, "The thermometer's red line shoots up and the bulb pops"),
        ("cam", "trio"),
        ("sfx", "rumble_big"),
        ("beat", "big_rumble", 2.0, "Violent rumble, the water starts to boil"),
        ("cam", "barry_cu"),
        ("say", "barry", "Seriously? The one time?", dict(mood="deadpan")),
        ("cam", "volcano"),
        ("sfx", "explosion"),
        ("music", "action", dict(fade=0.05)),
        ("beat", "eruption", 3.5, "Mount Snooze erupts: plume, lava fountains, red sky"),
        ("cam", "trio"),
        ("say", "sunny", "Barry! What do we do?", dict(mood="panic")),
        ("say", "barry", "Everybody to the raft! Follow the signs! The stupid signs I made!", dict(mood="panic")),
        ("beat", "helmet_back", 0.8, "Barry slams the helmet back on"),
        ("sfx", "bonk"), ("sfx", "splat", dict(offset=0.05)),
        ("beat", "rocks_fall", 2.0, "Rocks rain down; one bonks Doreen's orange into juice"),
        ("say", "doreen", "My orange!", dict(mood="shock")),
        ("cam", "escape"),
        ("beat", "run_to_raft", 3.5, "Everyone scrambles out past the EXIT signs and leaps onto the raft"),
        ("sfx", "big_splash"),
        ("beat", "raft_launch", 2.5, "The raft shoots down the river as lava pours into the spring behind them"),
    ]),
    dict(id="s08_aftermath", setting="river_sunset", music="sunset", transition="fade", events=[
        ("cam", "raft_wide"),
        ("pause", 1.5),
        ("say", "sunny", "Barry. Bro. You were right.", dict(mood="sad")),
        ("say", "doreen", "You were right about everything. The water. The mountain. The fish.", dict(mood="sad")),
        ("cam", "gerald_flag"),
        ("say", "gerald", "And me, to be fair.", dict(mood="smug")),
        ("cam", "raft_wide"),
        ("say", "barry", "And the vulture. Thank you, Gerald.", dict(mood="deadpan")),
        ("cam", "barry_cu"),
        ("say", "barry", "Could you say it again? Slower? I want to remember where I was.", dict(mood="smug")),
        ("cam", "sunny_cu"),
        ("say", "sunny", "You. Were. Right.", dict(mood="chill", speed=0.75)),
        ("cam", "barry_cu"),
        ("say", "barry", "Huh. My whole life I wondered what being right would feel like. And it feels... fantastic. I feel...", dict(mood="happy")),
        ("beat", "doreen_orange", 1.2, "Doreen gently places an orange on Barry's head"),
        ("say", "barry", "Chill. Is this it? Am I chill?", dict(mood="chill")),
        ("cam", "raft_wide"),
        ("say", "sunny", "Welcome to chill, bro.", dict(mood="happy")),
        ("pause", 1.0),
    ]),
    dict(id="s09_epilogue", setting="new_spring", music="lounge", transition="fade", events=[
        ("beat", "three_weeks_later", 2.2, "Caption: THREE WEEKS LATER"),
        ("cam", "trio"),
        ("say", "sunny", "Barry? Is the water warmer today? Should I be tracking this?", dict(mood="worried")),
        ("cam", "barry_cu"),
        ("say", "barry", "Relax, Sunny. Hot is a temperature.", dict(mood="chill")),
        ("sfx", "flap"),
        ("beat", "gerald_returns", 1.6, "Gerald gently lands on Barry's head again"),
        ("pause", 0.8),
        ("beat", "barry_eye_opens", 0.8, "Barry's eyes slowly open"),
        ("say", "gerald", "No reason.", dict(mood="smug")),
        ("cam", "trio"),
        ("say", "barry", "Everybody on the raft!", dict(mood="panic", gap=0.15)),
        ("sfx", "sting_bad"),
    ]),
    dict(id="s10_end", setting="title", music="jazz_end", transition="cut", tail=0.5, events=[
        ("beat", "end_card", 6.0, "'CHILL CAPYBARA' then 'THE END' on black, jazz button"),
    ]),
]
